# vault-mcp installer for Windows — https://github.com/videnovnebojsa/vault-mcp
#
# Usage:
#   irm https://raw.githubusercontent.com/videnovnebojsa/vault-mcp/main/install.ps1 | iex
#   .\install.ps1                      # install or upgrade
#   .\install.ps1 -Configure           # reconfigure only (skip binary download)
#   .\install.ps1 -LocalBin <path>     # stage a locally built binary (skip download; CI/dev)
#   .\install.ps1 -NoService           # skip background service prompt (useful for CI)
#
# Requires: PowerShell 5.1+, Windows x64

[CmdletBinding()]
param(
    [switch]$Configure,     # skip binary download, reconfigure only
    [string]$LocalBin = "", # stage a locally built binary instead of downloading (CI/dev)
    [switch]$NoService      # skip background service installation prompt (useful for CI)
)

$ErrorActionPreference = 'Stop'

# ─── Constants ────────────────────────────────────────────────────────────────

$REPO       = "videnovnebojsa/vault-mcp"
$ARTIFACT   = "vault-mcp-windows-x64.exe"
$BIN_DIR    = Join-Path $env:LOCALAPPDATA "vault-mcp"
$BIN_PATH   = Join-Path $BIN_DIR "vault-mcp.exe"
$VBS_PATH   = Join-Path $BIN_DIR "launch-hidden.vbs"
$CFG_DIR    = Join-Path $env:APPDATA "vault-mcp"
$CFG_FILE   = Join-Path $CFG_DIR ".env"
$VER_FILE   = Join-Path $CFG_DIR ".installed-version"

# ─── Helpers ──────────────────────────────────────────────────────────────────

function Write-Step  { Write-Host "→ $args" -ForegroundColor Cyan }
function Write-Ok    { Write-Host "✔ $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "⚠ $args" -ForegroundColor Yellow }
function Write-Err   { Write-Host "✘ Error: $args" -ForegroundColor Red; throw "install failed: $args" }

function Get-CfgValue([string]$Key) {
    if (-not (Test-Path $CFG_FILE)) { return "" }
    $line = Get-Content $CFG_FILE | Where-Object { $_ -match "^${Key}=" } | Select-Object -First 1
    if ($line) { return ($line -split "=", 2)[1].Trim('"') }
    return ""
}

function Prompt-Input([string]$Message, [string]$Default) {
    if ($Default) {
        Write-Host -NoNewline "${Message} [${Default}]: " -ForegroundColor White
    } else {
        Write-Host -NoNewline "${Message}: " -ForegroundColor White
    }
    $userInput = Read-Host
    if ([string]::IsNullOrWhiteSpace($userInput)) { return $Default }
    return $userInput
}

# schtasks writes to stderr (and returns non-zero) when a task is absent — expected on
# a first install. Under $ErrorActionPreference='Stop' that stderr surfaces as a
# terminating NativeCommandError and aborts the script before the task is registered.
# Run schtasks with the error preference relaxed and stderr merged into stdout so we
# observe the exit code instead of throwing.
function Invoke-Schtasks([string[]]$SchtasksArgs) {
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        # Reset to a sentinel first: if schtasks fails to launch at all, $LASTEXITCODE
        # retains the previous native command's value and a stale 0 would be misread as
        # success. Seeding non-zero means a no-launch is reported as failure.
        $global:LASTEXITCODE = -1
        # Capture combined output so callers can surface schtasks' own message on failure.
        $script:SchtasksOutput = (& schtasks @SchtasksArgs 2>&1 | Out-String).Trim()
        return $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prev
    }
}

# The scheduled task launches the server through this VBScript shim rather than the exe
# directly. vault-mcp.exe is a console app, so Task Scheduler pops a black console window
# on every login/restart — the task's Hidden flag does not suppress it. wscript runs the
# exe with window style 0 (hidden). Rewritten whenever the exe is (re)staged.
function Write-VbsLauncher {
    # The exe path must stay quoted inside the command string so a username with spaces
    # (e.g. C:\Users\John Doe\...) is passed as one argument. In a VBScript string literal
    # a literal double-quote is written by doubling it, so the path is wrapped in """...""".
    $escaped = $BIN_PATH -replace '"', '""'
    $vbs = @"
' Generated by vault-mcp install.ps1 — launches the server with no console window.
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run """$escaped""", 0, False
"@
    # Default = system ANSI codepage, which wscript expects for a BOM-less .vbs; ASCII would
    # mangle a path containing non-ASCII characters (e.g. an accented username).
    $vbs | Set-Content -Path $VBS_PATH -Encoding Default
}

# Claude Desktop's config lives in different places depending on the build. The classic
# desktop installer uses %APPDATA%\Claude; the Microsoft Store (AppX) build redirects it
# into the package container. Probe both and report what actually exists.
function Get-ClaudeDesktopConfigPaths {
    $standard = Join-Path $env:APPDATA "Claude\claude_desktop_config.json"
    $msStore  = Join-Path $env:LOCALAPPDATA "Packages\Claude_pzs8sxrjxfjjc\LocalCache\Roaming\Claude\claude_desktop_config.json"
    $found = @()
    if (Test-Path $standard) { $found += $standard }
    if (Test-Path $msStore)  { $found += $msStore }
    return [PSCustomObject]@{ Standard = $standard; MsStore = $msStore; Found = $found }
}

# (Re)create the scheduled task from the current XML and start it. Used by both first
# install and -Configure — a -Configure run must rewrite the task so existing installs
# that point straight at the exe adopt the hidden wscript launcher. /F overwrites in place.
function Install-VaultTask {
    $xmlPath = Join-Path $env:TEMP "vault-mcp-task.xml"
    # XML-escape the interpolated paths: a profile path may legitimately contain '&'
    # (Windows allows it in account/folder names), which would otherwise produce malformed
    # XML and a cryptic schtasks /Create parse failure.
    $vbsPathXml = [System.Security.SecurityElement]::Escape($VBS_PATH)
    $cfgDirXml  = [System.Security.SecurityElement]::Escape($CFG_DIR)
    $xml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>vault-mcp MCP server</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <StartWhenAvailable>true</StartWhenAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Enabled>true</Enabled>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>999</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>wscript.exe</Command>
      <Arguments>"$vbsPathXml"</Arguments>
      <WorkingDirectory>$cfgDirXml</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"@
    $xml | Set-Content -Path $xmlPath -Encoding Unicode
    # /End first so /Create /F can replace a task whose instance is currently running.
    [void](Invoke-Schtasks @("/End", "/TN", "vault-mcp"))
    $rc = Invoke-Schtasks @("/Create", "/TN", "vault-mcp", "/XML", $xmlPath, "/F")
    Remove-Item $xmlPath -Force
    if ($rc -ne 0) { Write-Err "Failed to register scheduled task (schtasks exit code $rc): $script:SchtasksOutput" }
    if ((Invoke-Schtasks @("/Run", "/TN", "vault-mcp")) -ne 0) {
        Write-Warn "Service registered but did not start — it will start at next logon, or run: schtasks /Run /TN vault-mcp"
    } else {
        Write-Ok "Service registered in Task Scheduler and started"
    }
    Write-Host "  Restart: " -NoNewline
    Write-Host 'schtasks /End /TN vault-mcp; schtasks /Run /TN vault-mcp' -ForegroundColor Cyan
}

# ─── Banner ───────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "vault-mcp installer" -ForegroundColor White -BackgroundColor DarkBlue
Write-Host "────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""

# ─── Step 1: Architecture check ───────────────────────────────────────────────

if (-not [Environment]::Is64BitOperatingSystem) {
    Write-Err "vault-mcp requires a 64-bit Windows installation"
}

# ─── Steps 2-4: Download binary ───────────────────────────────────────────────

if (-not $Configure -and $LocalBin) {
    # ─── Local binary mode (-LocalBin) ──────────────────────────────────────────
    # Used by CI and local dev builds — skips GitHub download entirely.
    if (-not (Test-Path $LocalBin -PathType Leaf)) { Write-Err "Local binary not found: $LocalBin" }
    New-Item -ItemType Directory -Force -Path $BIN_DIR | Out-Null
    New-Item -ItemType Directory -Force -Path $CFG_DIR | Out-Null
    Copy-Item -Force -Path $LocalBin -Destination $BIN_PATH
    Set-Content -Path $VER_FILE -Value "local" -NoNewline
    Write-Ok "Binary staged from $LocalBin → $BIN_PATH (local)"
} elseif (-not $Configure) {
    Write-Step "Checking latest release..."
    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$REPO/releases/latest"
    $LATEST_TAG = $release.tag_name
    if (-not $LATEST_TAG) { Write-Err "Could not fetch latest release tag — check your internet connection" }
    Write-Step "Latest release: $LATEST_TAG"

    $INSTALLED_TAG = if (Test-Path $VER_FILE) { Get-Content $VER_FILE -Raw } else { "" }
    $INSTALLED_TAG = $INSTALLED_TAG.Trim()

    if ($LATEST_TAG -notmatch '^v\d+\.\d+') {
        Write-Err "Unexpected release tag format: '$LATEST_TAG' — GitHub API may be rate-limiting"
    }

    if ((Test-Path $BIN_PATH) -and ($INSTALLED_TAG -eq $LATEST_TAG)) {
        Write-Ok "Already on $LATEST_TAG — skipping download"
    } else {
        if ($INSTALLED_TAG) {
            Write-Step "Upgrading $INSTALLED_TAG → $LATEST_TAG..."
        } else {
            Write-Step "Downloading $ARTIFACT..."
        }
        New-Item -ItemType Directory -Force -Path $BIN_DIR | Out-Null
        $DOWNLOAD_URL = "https://github.com/$REPO/releases/download/$LATEST_TAG/$ARTIFACT"
        $TMP_PATH = "$BIN_PATH.tmp"
        try {
            Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $TMP_PATH -UseBasicParsing
            Move-Item -Force -Path $TMP_PATH -Destination $BIN_PATH
        } catch {
            if (Test-Path $TMP_PATH) { Remove-Item $TMP_PATH -Force }
            Write-Err "Download failed from $DOWNLOAD_URL : $_"
        }
        New-Item -ItemType Directory -Force -Path $CFG_DIR | Out-Null
        Set-Content -Path $VER_FILE -Value $LATEST_TAG -NoNewline
        Write-Ok "Binary installed: $BIN_PATH ($LATEST_TAG)"
    }
}

# ─── Step 5: Configuration ────────────────────────────────────────────────────

New-Item -ItemType Directory -Force -Path $CFG_DIR | Out-Null
Write-Host ""
Write-Host "Configuration" -ForegroundColor White
Write-Host ("─" * 13)
Write-Host "Settings file: " -NoNewline; Write-Host $CFG_FILE -ForegroundColor Cyan
Write-Host ""

# Vault path (required)
$currentVault = Get-CfgValue "OBSIDIAN_VAULT_PATH"
$VAULT_PATH = Prompt-Input "Vault path (e.g. C:\Users\you\Documents\obsidian)" $currentVault
if ([string]::IsNullOrWhiteSpace($VAULT_PATH)) { Write-Err "Vault path is required" }
$VAULT_PATH = $VAULT_PATH -replace "^~", $env:USERPROFILE
if (-not (Test-Path $VAULT_PATH -PathType Container)) {
    Write-Err "Directory not found: $VAULT_PATH"
}

# Port
$currentPort = Get-CfgValue "MCP_PORT"
if (-not $currentPort) { $currentPort = "3782" }
$MCP_PORT = Prompt-Input "Port" $currentPort
if ($MCP_PORT -notmatch '^\d+$') { Write-Err "Port must be a number" }

# API key
$currentKey = Get-CfgValue "MCP_API_KEY"
if ($currentKey) {
    $keyInput = Prompt-Input "API key (leave blank to keep current)" ""
    $MCP_API_KEY = if ($keyInput) { $keyInput } else { $currentKey }
} else {
    $MCP_API_KEY = Prompt-Input "API key (optional — leave empty for local-only)" ""
}

# Embeddings
$currentEmb = Get-CfgValue "ENABLE_EMBEDDINGS"
if (-not $currentEmb) { $currentEmb = "false" }
if ($currentEmb -eq "true") {
    $answer = Prompt-Input "Keep vector embeddings enabled? [Y/n]" "Y"
    $ENABLE_EMBEDDINGS = if ($answer -match '^[Nn]') { "false" } else { "true" }
} else {
    $answer = Prompt-Input "Enable vector embeddings? [y/N]" "N"
    $ENABLE_EMBEDDINGS = if ($answer -match '^[Yy]') { "true" } else { "false" }
}

$EMBEDDINGS_ENDPOINT = ""
$EMBEDDINGS_API_KEY  = ""
if ($ENABLE_EMBEDDINGS -eq "true") {
    $currentEmbUrl = Get-CfgValue "EMBEDDING_ENDPOINT"
    if (-not $currentEmbUrl) { $currentEmbUrl = "https://api.openai.com/v1" }
    $EMBEDDINGS_ENDPOINT = Prompt-Input "Embeddings endpoint" $currentEmbUrl

    $currentEmbKey = Get-CfgValue "EMBEDDING_API_KEY"
    if ($currentEmbKey) {
        $embKeyInput = Prompt-Input "Embeddings API key (leave blank to keep current)" ""
        $EMBEDDINGS_API_KEY = if ($embKeyInput) { $embKeyInput } else { $currentEmbKey }
    } else {
        $EMBEDDINGS_API_KEY = Prompt-Input "Embeddings API key" ""
    }
}

# Write config file atomically (temp file → Move-Item to avoid partial writes)
$cfg = @(
    "# vault-mcp configuration"
    "# Generated by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd')"
    "# Full config reference: https://github.com/$REPO/blob/main/docs/configuration.md"
    "# Interactive editor (requires Bun): bun run configure"
    ""
    "OBSIDIAN_VAULT_PATH=`"$VAULT_PATH`""
    "MCP_PORT=$MCP_PORT"
)
if ($MCP_API_KEY)         { $cfg += "MCP_API_KEY=`"$MCP_API_KEY`"" }
$cfg += "ENABLE_EMBEDDINGS=$ENABLE_EMBEDDINGS"
if ($EMBEDDINGS_ENDPOINT) { $cfg += "EMBEDDING_ENDPOINT=`"$EMBEDDINGS_ENDPOINT`"" }
if ($EMBEDDINGS_API_KEY)  { $cfg += "EMBEDDING_API_KEY=`"$EMBEDDINGS_API_KEY`"" }

$CFG_TMP = "$CFG_FILE.tmp"
$cfg | Set-Content -Path $CFG_TMP
# Restrict file to current user only
$acl = Get-Acl $CFG_TMP
$acl.SetAccessRuleProtection($true, $false)
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
    "FullControl", "Allow")
$acl.AddAccessRule($rule)
Set-Acl -Path $CFG_TMP -AclObject $acl
Move-Item -Force -Path $CFG_TMP -Destination $CFG_FILE
Write-Ok "Config written to $CFG_FILE"

# ─── Step 6: Add to PATH and register Task Scheduler ─────────────────────────

Write-Host ""
Write-Host "Background service" -ForegroundColor White
Write-Host ("─" * 18)

# Ensure BIN_DIR is in user PATH
$userPath = [Environment]::GetEnvironmentVariable("PATH", "User")
if ($userPath -notlike "*$BIN_DIR*") {
    [Environment]::SetEnvironmentVariable("PATH", "$userPath;$BIN_DIR", "User")
    Write-Ok "Added $BIN_DIR to your user PATH (restart your terminal to take effect)"
}

# Refresh the hidden-launch shim the scheduled task points at (covers install, upgrade,
# and -Configure). BIN_DIR exists by now on any normal run, but ensure it for -Configure.
New-Item -ItemType Directory -Force -Path $BIN_DIR | Out-Null
Write-VbsLauncher

if ($NoService) {
    Write-Step "Service install skipped (-NoService)"
} else {
    # Check if task already exists (schtasks errors when absent — Invoke-Schtasks handles it)
    $taskRegistered = (Invoke-Schtasks @("/Query", "/TN", "vault-mcp")) -eq 0

    if ($taskRegistered -and $Configure) {
        # Re-create so an existing task that pointed straight at the exe adopts the new
        # hidden wscript launcher, then start it with the refreshed config.
        Install-VaultTask
    } else {
        $answer = Prompt-Input "Install as a background service (auto-starts at login)? [Y/n]" "Y"
        if ($answer -notmatch '^[Nn]') {
            Install-VaultTask
        } else {
            Write-Step "Service install skipped. Start manually: vault-mcp"
        }
    }
}

# ─── Step 7: Connection instructions ─────────────────────────────────────────

Write-Host ""
Write-Host "Connect Claude Code" -ForegroundColor White
Write-Host ("─" * 19)
Write-Host "Add to " -NoNewline; Write-Host ".mcp.json" -ForegroundColor Cyan -NoNewline; Write-Host " in your project root:"
Write-Host @"
{
  "mcpServers": {
    "vault": { "type": "http", "url": "http://127.0.0.1:$MCP_PORT/mcp" }
  }
}
"@

Write-Host ""
Write-Host "Connect Claude Desktop" -ForegroundColor White
Write-Host ("─" * 22)
Write-Host "How it fits together:"
Write-Host "  • The background service above runs the HTTP server (vault-mcp.exe, no args)."
Write-Host "  • Claude Desktop speaks stdio, not HTTP, so it spawns vault-mcp.exe bridge"
Write-Host "    on demand — a stdio↔HTTP proxy to that running server, not a second server."
Write-Host ""

# Claude Desktop's config path differs between the classic and Microsoft Store builds.
# Point the user at the file that actually exists rather than a single hardcoded path.
$cdCfg = Get-ClaudeDesktopConfigPaths
if ($cdCfg.Found.Count -eq 1) {
    Write-Host "Add to " -NoNewline; Write-Host $cdCfg.Found[0] -ForegroundColor Cyan -NoNewline; Write-Host ":"
} elseif ($cdCfg.Found.Count -gt 1) {
    Write-Host "Add to your Claude Desktop config — edit whichever your build uses:"
    foreach ($p in $cdCfg.Found) { Write-Host "  " -NoNewline; Write-Host $p -ForegroundColor Cyan }
} else {
    Write-Host "Add to your " -NoNewline; Write-Host "claude_desktop_config.json" -ForegroundColor Cyan -NoNewline; Write-Host ":"
    Write-Host "  Classic build:  " -NoNewline; Write-Host $cdCfg.Standard -ForegroundColor Cyan
    Write-Host "  MS Store build: " -NoNewline; Write-Host $cdCfg.MsStore -ForegroundColor Cyan
}
# Escape backslashes so the Windows binary path is valid JSON.
$binJson = $BIN_PATH -replace '\\', '\\'
Write-Host @"
{
  "mcpServers": {
    "vault": {
      "command": "$binJson",
      "args": ["bridge"],
      "env": { "VAULT_MCP_URL": "http://127.0.0.1:$MCP_PORT/mcp" }
    }
  }
}
"@

Write-Host ""
Write-Host "Verify" -ForegroundColor White
Write-Host ("─" * 6)
Write-Host "  " -NoNewline; Write-Host "curl http://localhost:$MCP_PORT/health" -ForegroundColor Cyan

Write-Host ""
Write-Host "Reconfigure anytime" -ForegroundColor White
Write-Host ("─" * 19)
Write-Host "  " -NoNewline; Write-Host ".\install.ps1 -Configure" -ForegroundColor Cyan -NoNewline
Write-Host "   — quick wizard (no download)"
Write-Host "  " -NoNewline; Write-Host "bun run configure" -ForegroundColor Cyan -NoNewline
Write-Host "          — full editor (requires Bun)"
Write-Host "  " -NoNewline; Write-Host $CFG_FILE -ForegroundColor Cyan -NoNewline
Write-Host "  — edit directly"

Write-Host ""
Write-Host "✔ Done! vault-mcp is ready." -ForegroundColor Green
Write-Host ""
